# Setup
title:               Jeongtaek Oh (오정택) | Ph.D Candidate
tagline:             ''
url:                 https://taekkii.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeongtaek Oh
  url:               https://taekkii.github.io
  email:             ohjtgood@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
