# Setup
title:               Taeryung Lee (이태룡) | Ph.D Candidate
tagline:             ''
url:                 https://taeryunglee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Taeryung Lee
  url:               https://taeryunglee.github.io
  email:             trlee94@snu.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
